REL-2155 Update SonarQube to 8.9.7
SonarSource/helm-chart-sonarqube pull request #170
Opened 2022-02-04 13:26 UTC by philippe-perrin-sonarsource

2022-02-04 13:46 UTC, tobias-trabelsi-sonarsource reviewed
QA can only be green when images are available

2022-02-04 13:46 UTC, tobias-trabelsi-sonarsource commented on charts/sonarqube-lts/Chart.yaml
>      - kind: fixed
The previous fix can be removed from the list. It is already live on [artifacthub](https://artifacthub.io/packages/helm/sonarqube/sonarqube-lts?modal=changelog)

2022-02-04 15:32 UTC, philippe-perrin-sonarsource commented
> QA can only be green when images are available

Interresting, this isn't what's stated in the doc. I'll update it.

2022-02-07 07:17 UTC, tobias-trabelsi-sonarsource requested changes
images are available, so just the annotation left

2022-02-07 07:54 UTC, tobias-trabelsi-sonarsource approved these changes
LGTM :+1:

2022-02-07 07:55 UTC, merged