Fix spelling error in sonarqube-lts App sts: "initFS.enabeld" -> "initFs.enabled"
SonarSource/helm-chart-sonarqube pull request #180
Opened 2022-02-21 16:09 UTC by danragnar

Please ensure your pull request adheres to the following guidelines:
- [X] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [X] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`
- [X] Bump the Version number of the respected chart

Fixes spelling error in the App Statefulset for enabling or disabling the initFs initContainer.

2022-02-22 09:06 UTC, wouter-admiraal-sonarsource requested changes
Hi @danragnar , thank you very much for your contribution.

Unfortunately, this is a breaking change. We would have to make it backward compatible. I made a few suggestion.

2022-02-22 09:06 UTC, wouter-admiraal-sonarsource commented on charts/sonarqube-lts/templates/sonarqube-sts.yaml
> +      {{- if and .Values.persistence.enabled .Values.initFs.enabled }}
In order to keep the previous "faulty" value for backwards compatibility, how about something like (to be adapted):

```suggestion
      {{- if and .Values.persistence.enabled ( or .Values.initFs.enabeld .Values.initFs.enabled ) }}
```

2022-02-22 13:55 UTC, danragnar commented
> Hi @danragnar , thank you very much for your contribution.
> 
> Unfortunately, this is a breaking change. We would have to make it backward compatible. I made a few suggestion.

Yeah, seems like a good idea. I have added your proposed changes.

2022-02-24 14:22 UTC, wouter-admiraal-sonarsource commented
🤦  I just realized this is targetting our LTS chart. This is contrary to our policy: we only provide updates if there's a security vulnerability or a major degradation in functionality. A typo in a configuration file, although kind of dumb, is not a valid reason to update our chart.

I'm really sorry I didn't notice this earlier. I'm going to have to close this PR. Thank you again for taking the time to open a PR and to attempt to fix this. It's really appreciated.

2022-02-24 14:22 UTC, closed without merging

2022-02-25 13:50 UTC, danragnar commented
I understand. But what you can do is fix the documentation so that when someone wants to disable the initFs initcontainer, they're not set out on a 2 hour troubleshooting extravaganza as I was...

2022-02-25 14:51 UTC, wouter-admiraal-sonarsource commented
That's a fair point 👍 . Updated it here: https://github.com/SonarSource/helm-chart-sonarqube/blob/master/charts/sonarqube-lts/README.md