DOCKER-81 Add support for monitoringPasscode passed as a secret and removal of in-clear-text livenessprobe httpheader
SonarSource/helm-chart-sonarqube pull request #252
Opened 2022-08-26 09:33 UTC by carminevassallo

Currently, we cannot load the monitoringPasscode from an existing secret and we define it among liveness HTTP headers in clear text (DOCKER-65).

In this PR, we add the possibility to get this value from a secret and define a new liveness probe that masks the HTTP header.

2022-08-29 11:58 UTC, leo-geoffroy-sonarsource commented
I think we should not create the default secret `{{ template "sonarqube.fullname" . }}-monitoring-passcode` when we provision monitoringPasscodeSecretName and monitoringPasscodeSecretKey.
It is failing on my side since `.Values.monitoringPasscode` is not defined

2022-08-29 11:58 UTC, leo-geoffroy-sonarsource requested changes
see comment above

2022-08-29 12:49 UTC, carminevassallo commented
> I think we should not create the default secret `{{ template "sonarqube.fullname" . }}-monitoring-passcode` when we provision monitoringPasscodeSecretName and monitoringPasscodeSecretKey. It is failing on my side since `.Values.monitoringPasscode` is not defined

Hi @leo-geoffroy-sonarsource,

thanks I just have a question. Isn't `monitoringPasscode` always defined in the values.yml? By default, we always have this value set to a dummy password (I'm referring to [this line](https://github.com/SonarSource/helm-chart-sonarqube/blob/2a3bed2f63fee521223a3bc1e085d9baf583d8bd/charts/sonarqube/values.yaml#L299)), so it should not happen that `monitoringPasscode` is unset. Am I right? Could it be that you were creating a secret having the same name and this was causing the error?

2022-08-29 14:46 UTC, leo-geoffroy-sonarsource commented on charts/sonarqube-dce/values.yaml
> +# monitoringPasscodeSecretName: "passSecretName"
maybe use a valid secret name as example

2022-09-01 12:01 UTC, leo-geoffroy-sonarsource approved these changes
LGTM

2022-09-01 12:02 UTC, merged