DRAFT: DOCKER-73: allow test image to be configurable in helm chart
SonarSource/helm-chart-sonarqube pull request #259
Opened 2022-09-27 07:26 UTC by jCOTINEAU

- Add Values parameter tests.image
- Update Outdated README

Please ensure your pull request adheres to the following guidelines:
- [ ] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`
- [ ] Bump the Version number of the respected chart

2022-09-27 17:02 UTC, carminevassallo requested changes
Thanks for spotting the wrong usage  of `tests.image`! This PR can be both viewed as feature enhancement and bug fix but at least originally this was meant to be the former, so I suggest that we increment the minor instead of patch version. I've tested locally, the generated k8s are the same as before, I added a few small comments and probably we should replace the deprecated image. @leo-geoffroy-sonarsource, could you please give a second review?

2022-09-28 07:47 UTC, leo-geoffroy-sonarsource commented
Nitpick - You can remove the colon ":" in your commit message, as a general rule we just keep space between ticket number and comment

2022-09-28 07:52 UTC, leo-geoffroy-sonarsource commented
> Thanks for spotting the wrong usage of `tests.image`! This PR can be both viewed as feature enhancement and bug fix but at least originally this was meant to be the former, so I suggest that we increment the minor instead of patch version. I've tested locally, the generated k8s are the same as before, I added a few small comments and probably we should replace the deprecated image. @leo-geoffroy-sonarsource, could you please give a second review?

Agreed with the minor version increase, it is indeed an improvement
Good spot on the deprecated image minideb-extras, and I suggest opening a different task for that as this will requires a bit of investigation/testing (I'm curious about the functional differences between minideb-extras and minideb)

2022-09-28 07:53 UTC, leo-geoffroy-sonarsource commented on charts/sonarqube-dce/Chart.yaml
> +version: 4.2.2
See [my comment](https://github.com/SonarSource/helm-chart-sonarqube/pull/259#issuecomment-1260523773)

2022-09-28 09:31 UTC, jCOTINEAU commented
> > Thanks for spotting the wrong usage of `tests.image`! This PR can be both viewed as feature enhancement and bug fix but at least originally this was meant to be the former, so I suggest that we increment the minor instead of patch version. I've tested locally, the generated k8s are the same as before, I added a few small comments and probably we should replace the deprecated image. @leo-geoffroy-sonarsource, could you please give a second review?
> 
> Agreed with the minor version increase, it is indeed an improvement Good spot on the deprecated image minideb-extras, and I suggest opening a different task for that as this will requires a bit of investigation/testing (I'm curious about the functional differences between minideb-extras and minideb)

I think we could ship the minideb-extras into minideb change, as the only purpose is running a curl command, and it is directly tested by the CI process.

What do you think ?

2022-09-28 09:42 UTC, jCOTINEAU commented on charts/sonarqube-dce/values.yaml
> +  image: bitnami/minideb-extras
resolving with [this](https://github.com/SonarSource/helm-chart-sonarqube/pull/259#issuecomment-1260641671), adding a ticket

2022-09-28 10:51 UTC, carminevassallo approved these changes

2022-09-28 10:54 UTC, carminevassallo commented
> Well the minideb does not contain curl so definitely a scope for another tickets

oh ok! can you please create one (if you haven't done it already)? Apart from that, I'm fine with the changes, what about you @leo-geoffroy-sonarsource ?

2022-09-28 11:12 UTC, leo-geoffroy-sonarsource approved these changes
LGTM

2022-09-28 12:22 UTC, merged