SQHELM-118 fix unsupported wget parameter
SonarSource/helm-chart-sonarqube pull request #312
Opened 2023-03-24 13:18 UTC by jCOTINEAU

2023-03-24 16:06 UTC, carminevassallo requested changes

2023-03-24 16:06 UTC, carminevassallo commented on charts/sonarqube-dce/CHANGELOG.md
> +## [9.3.0]
We should align the changelog with the new chart version :)

2023-03-24 16:06 UTC, carminevassallo commented on charts/sonarqube-dce/Chart.yaml
> +version: 8.3.0
We should bump the patch version for bug fixes..

2023-03-24 16:06 UTC, carminevassallo commented on charts/sonarqube-dce/Chart.yaml
> +      description: "Fixed unsupported wget parameter `--proxy off` with `--no-proxy`"
are these descriptions rendered as markdown by the changelog section of ArtifactHub.io?

2023-03-24 16:06 UTC, carminevassallo commented on charts/sonarqube/Chart.yaml
> +version: 9.5.0
same comment about the patch version..

2023-03-27 15:32 UTC, carminevassallo approved these changes
LGTM!

2023-03-28 07:10 UTC, merged

2023-03-29 00:47 UTC, bbodenmiller commented
Any chance this can be backported to 8.x chart? Or a workaround that folks affected by this could put in place while waiting? We manually removed readiness probe but it seems there should be a better solution.

2023-03-30 15:10 UTC, jCOTINEAU commented
Hello @bbodenmiller, it is not planed yet, i will grab some information and get back to you soon.

Right now as a quick workaround you could use helm post render to kustomize those probe and replace them with the correct options.

I am really sorry for the inconvenience.