[WIP] Release SonarQube 10.5.1
SonarSource/helm-chart-sonarqube pull request #478
Opened 2024-04-30 09:50 UTC by davividal

2024-04-30 09:51 UTC, davividal commented
WIP as we are waiting for https://github.com/docker-library/official-images/pull/16690 to be merged.

2024-05-02 08:11 UTC, carminevassallo requested changes
Hey Davi,

Thanks for opening the PRs. I noticed a few improvements to make:

- In both charts, we should add the change about "Upgrade SonarQube to 10.5.1". So far, we only have the chart's update.
- a small typo on gcp

2024-05-02 08:11 UTC, carminevassallo commented on google-cloud-marketplace-k8s-app/schema.yaml
> +      Releasing SonarQube 10.5charts/sonarqube/values.yaml.x as a google cloud k8s marketplace application
Typo here

2024-05-02 08:19 UTC, davividal commented on google-cloud-marketplace-k8s-app/schema.yaml
> +      Releasing SonarQube 10.5charts/sonarqube/values.yaml.x as a google cloud k8s marketplace application
Ops! `Ctrl+V` in the wrong window...

2024-05-02 14:02 UTC, carminevassallo approved these changes
LGTM 🚀

2024-05-02 14:52 UTC, merged