SONAR-22353 Define the HorizontalPodAutoscaler for the app deployment
SonarSource/helm-chart-sonarqube pull request #491
Opened 2024-06-12 17:24 UTC by carminevassallo

2024-06-13 07:13 UTC, jCOTINEAU requested changes
Super cool improvement!

I think we should also change the deployment behavior as described [here](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#migrating-deployments-and-statefulsets-to-horizontal-autoscaling) to make sure that on deploy we do not overwrite the hpa count.

2024-06-13 07:19 UTC, jCOTINEAU commented on charts/sonarqube-dce/values.yaml
> +            periodSeconds: 0
also when trying to install it by only changing `enabled:true` I get this error
`Error: UPGRADE FAILED: failed to create resource: HorizontalPodAutoscaler.autoscaling "toto-sonarqube-dce-app-hpa" is invalid: [spec.behavior.scaleUp.policies[0].periodSeconds: Invalid value: 0: must be greater than zero, spec.behavior.scaleDown.policies[0].periodSeconds: Invalid value: 0: must be greater than zero] `

2024-06-19 08:33 UTC, jCOTINEAU approved these changes
lgtm! 

Small question, should we add the link to the official doc afterward ?

2024-06-19 09:46 UTC, carminevassallo commented
> Small question, should we add the link to the official doc afterward ?

Yup, we discussed this, we are gonna update the doc when ready.

2024-06-19 09:47 UTC, merged