NO-JIRA make automountServiceAccountToken in _pod.tpl configurable
SonarSource/helm-chart-sonarqube pull request #528
Opened 2024-08-07 14:30 UTC by vladimirddimov

Please ensure your pull request adheres to the following guidelines:
- [ ] explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
- [ ] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`

2024-08-07 14:34 UTC, marcvn-eng approved these changes

2024-08-26 09:17 UTC, jCOTINEAU commented
Hello @vladimirddimov, could i ask you to rebase and propagate the fix also to the DCE chart?

Also the changes are to be set in 10.7.0 as we are releasing at the same time as the upcoming SonarQube version.

Thanks a lot again for your contribution

2024-08-26 14:23 UTC, davividal requested changes

2024-08-26 14:23 UTC, davividal commented on charts/sonarqube/Chart.yaml
> +    - kind: changed
Please put your changes at the bottom.

2024-08-26 14:23 UTC, davividal commented on charts/sonarqube/templates/_pod.tpl
> +  automountServiceAccountToken: {{ .Values.podSpec.automountServiceAccountToken }}
Thank you for your contribution!

Can you please replicate your changes to the `sonarqube-dce` chart?

2024-09-16 12:44 UTC, jCOTINEAU commented
Hey @davividal, considering this PR has not received any updates, could you either close it or take over and build on top of the contribution?

2024-10-14 14:54 UTC, carminevassallo commented
As we don't see further reaction on this PR, we decided to create [a hardening ticket](https://sonarsource.atlassian.net/browse/SONAR-23395) about this feature.

Thanks again @vladimirddimov for your contribution.

2024-10-14 14:54 UTC, closed without merging