Add the possibility of to save the data with hostpath.
SonarSource/helm-chart-sonarqube pull request #605
Opened 2024-12-11 15:49 UTC by jbazp

Please ensure your pull request adheres to the following guidelines:
- [x] Sonarqube will not have more than one instance at a time, I want it to always run on a node and within that node save the information with hostpath, I do not want PVC or PV, I want to directly access the host disk to save it and it will go very quickly , easy and without intermediaries (Storage Provider).
- [x] Document your Changes in the `CHANGELOG.md` file of the respected chart as well as the `Chart.yaml`

2024-12-23 10:30 UTC, davividal commented
Hi @jbazp.

Thank you for your contribution. It looks like a cool improvement.

Could you please rebase your branch against the current master and provide a testing `values.yaml` under `tests/unit-compatibility-test/sonarqube`?

Can you also replicate this to the `sonarqube-dce` chart?

2024-12-27 10:43 UTC, jbazp commented
Hi @davividal! I made the changes you requested me, Can you check again?

2024-12-27 12:55 UTC, davividal requested changes
How did you generate both `tests/unit-compatibility-test/fixtures/sonarqube-dce/host-path-values.yaml` and `tests/unit-compatibility-test/fixtures/sonarqube/host-path-values.yaml`?

They look like a copy of `tests/dynamic-compatibility-test/sonarqube-dce/all-values.yaml` and `tests/dynamic-compatibility-test/sonarqube/all-values.yaml`.
Did you run the `.cirrus/generate_helm_fixtures.sh` script?

2024-12-27 12:55 UTC, davividal commented on charts/sonarqube-dce/CHANGELOG.md
> +* Add the possibility of to save the data with hostpath.
This must be under the `2025.1.0` version.

2024-12-27 12:55 UTC, davividal commented on charts/sonarqube-dce/Chart.yaml
> +version: 2025.1.1
This must remain as `2025.1.0`.

2024-12-27 13:26 UTC, jbazp commented on charts/sonarqube-dce/Chart.yaml
> +version: 2025.1.1
done

2024-12-27 13:36 UTC, jbazp commented
Yes! First, I created the values.yaml files: 
- tests/unit-compatibility-test/sonarqube/host-path-values.yaml]
- tests/unit-compatibility-test/sonarqube-dce/host-path-values.yaml
And finally, I ran .cirrus/generate_helm_fixtures.sh locally and it genereted me the following files:
- tests/unit-compatibility-test/fixtures/sonarqube/host-path-values.yaml
- tests/unit-compatibility-test/fixtures/sonarqube-dce/host-path-values.yaml

2025-01-08 08:30 UTC, jbazp commented
Hi @davividal! Do you need anything else?

2025-01-09 11:32 UTC, davividal requested changes
One last fix before I can merge this. :)

2025-01-09 11:32 UTC, davividal commented on charts/sonarqube/CHANGELOG.md
> +* Add the possibility of to save the data with hostpath.
This must be under `2025.1.0`.

2025-01-09 15:20 UTC, davividal commented
@jbazp can you rebase from master, please?

2025-01-09 16:10 UTC, jbazp commented
@davividal I did the rebase.

2025-01-21 09:08 UTC, jbazp commented
Hi @davividal! The PR is ready for to merge.

2025-02-03 10:40 UTC, davividal approved these changes
Thanks for this cool improvement, @jbazp!

I duplicated your PR on #631 so we can run our pipeline on your branch. Your fixture test case needs one minor fix, but I can do it.

2025-02-03 11:59 UTC, jbazp commented
Great @davividal! If there's anything I can help you with, just let me know.

2025-05-13 15:53 UTC, jCOTINEAU commented
Hello @jbazp , thanks again for your time and patience helping us grow our product trough community.

You can track the proposal in this [ticket](https://sonarsource.atlassian.net/browse/SONAR-24842), i am closing the PR for now, if we reopen, your commit will be used and you will be acknowledged as author.

We tackle community PR in batch during hardening sprints, i dont have yet an ETA for the feature.

Cheers, Jeremy.

2025-05-13 15:53 UTC, closed without merging

2025-06-17 09:04 UTC, davividal commented
If anyone is watching this, #631 was merged.